FROM debezium/connect:2.7.3.Final

COPY debezium-config.json /opt/kafka/config/
COPY setup-connector.sh /opt/kafka/bin/

USER root
RUN chmod +x /opt/kafka/bin/setup-connector.sh
USER kafka

ENTRYPOINT ["/opt/kafka/bin/setup-connector.sh"]